### PR TITLE
No need of symfony/twig-bridge, for it is not using any of the compon…

### PR DESCRIPTION
**Pull request by harikt**
…ents

I was looking at code and it looks there is no need of the `symfony/twig-bridge` . The only case is regarding the translation of the ui stuffs.

I also believe that integrating with puli will also help to some extends finding / loading templates from different location.

### CODE REVIEW

**Comment by benatespina** [comment]
Ey @harikt !

Thanks for your PR! But this library needs twig-bridge because the templates use the "trans" filter to make their content translatable ;)

**Comment by harikt** [comment]
Question is can't we just leave translation for the bridge and let the application / user do the stuff ?

**Comment by benatespina** [comment]
Decouple Twig from translation component is an overengineering that it does not have any benefit

**Comment by harikt** [comment]
cool. There was a misunderstanding regarding `symfony/twig-bridge` , I thought it was using the symfony/framework itself. I will close the same. Sorry about the hassle. Don't know how I noticed the wrong composer.json file .

**Pull request closed without merging**
