### PR TITLE
Add symfony/translation as a dependency.

### LINKED ISSUE #1: Templates rely in trans filter but not dependency missing in composer.json
We should add `symfony/twig-bridge` as a dependency? Or decouple from translation component?

### PR DESCRIPTION
**Pull request by harikt**
Fixes #1 .

We probably need to work on the docs for this how to register the translation etc.

### CODE REVIEW

**Comment by benatespina** [comment]
Yeah! The code, except oncoming unknown errors, is more or less finished but we need documented all the library and bundle with their bridges. Any help with that is welcome ;)

**Comment by harikt** [comment]
> Any help with that is welcome

Why not. Can send PR after I started to play more on these :) . I hope you guys can help me move when ever I am stuck :) . Is there a irc or google groups to talk, or github issues are fine for now ?

**Comment by gorkalaucirica** [comment]
Of course we appreciate a lot any help. Maybe gitter could be an interesting platform for collaboration. We have created a room so you can join us https://gitter.im/BenGorUser/User

**Comment by harikt** [comment]
not a fan of gitter though :-( .

**Comment by gorkalaucirica** [comment]
Well... we can keep talking in GitHub, the issues may serve as docs too...

**Pull request merged**
